// <auto-generated />
using System;
using MediUp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediUp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319234343_UpdateEntity-MaintenanceFilesHistory-HtmlContent")]
    partial class UpdateEntityMaintenanceFilesHistoryHtmlContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mup")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MediUp.Domain.Entities.Agent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("ElectricCompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("IdentityUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ElectricCompanyId");

                    b.ToTable("Agents", "mup");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.CenaceMeasurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CenaceCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("MeasurementDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TPLCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CenaceMeasurements", "mup");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.CenaceMeasurementDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CenaceMeasurementId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Hour")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CenaceMeasurementId");

                    b.ToTable("CenaceMeasurementDetails", "mup");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.ElectriCompany", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("longtext");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ElectriCompany", "mup");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.EnergyMeasurementData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ActiveEnergyDeliveredKwh")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ActiveEnergyReceivedKwh")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ApparentEnergyDeliveredKvah")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("AveragePowerFactor")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("AverageVoltageKv")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("EnergyMeasurementDownloadId")
                        .HasColumnType("bigint");

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<decimal>("Frequency")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("IntegrationPeriodSeconds")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MeasuredAt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("MeasuredAtIso")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("QuarterHour")
                        .HasColumnType("int");

                    b.Property<decimal>("ReactiveEnergyDeliveredKvarh")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ReactiveEnergyReceivedKvarh")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EnergyMeasurementDownloadId");

                    b.ToTable("EnergyMeasurementData", "mup");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.EnergyMeasurementDownload", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IntegrationStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("MeasurementDate")
                        .HasColumnType("date");

                    b.Property<string>("Meter")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlCapture")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlZip")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EnergyMeasurementDownloads", "mup");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.EnergyMeasurementEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("EnergyMeasurementDownloadId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EnergyMeasurementDownloadId");

                    b.ToTable("EnergyMeasurementEvents", "mup");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.LigtherMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("BatteryLevelPercent")
                        .HasColumnType("longtext");

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<string>("CENACECode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Class")
                        .HasColumnType("longtext");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gateway")
                        .HasColumnType("longtext");

                    b.Property<string>("InstallationLocation")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastCalibrationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MacAddress")
                        .HasColumnType("longtext");

                    b.Property<int>("ManufacturingYear")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("NetworkType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NextCalibrationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PrincipalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reference")
                        .HasColumnType("longtext");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetMask")
                        .HasColumnType("longtext");

                    b.Property<string>("SwitchLanPort")
                        .HasColumnType("longtext");

                    b.Property<long?>("SystemLigtherId")
                        .HasColumnType("bigint");

                    b.Property<string>("TPLCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TcRatio")
                        .HasColumnType("longtext");

                    b.Property<string>("TpRatio")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlCertificate")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlPicture")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SystemLigtherId");

                    b.ToTable("LigtherMetric", "mup");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.LigtherMetricStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ElectricCompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LigtherMetricStatusHistories", "mup");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.LigtherTransformer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<string>("Class")
                        .HasColumnType("longtext");

                    b.Property<string>("Codigo")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("ElectricCompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastCalibrationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NextCalibrationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("PrimaryCurrent")
                        .HasColumnType("double");

                    b.Property<double>("PrimaryVoltage")
                        .HasColumnType("double");

                    b.Property<double>("SecondaryCurrent")
                        .HasColumnType("double");

                    b.Property<double>("SecondaryVoltage")
                        .HasColumnType("double");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("SystemLigtherId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlCertificate")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlPicture")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SystemLigtherId");

                    b.ToTable("LigtherTransformers", "mup");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.LigtherTransformerMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("LigtherMetricId")
                        .HasColumnType("bigint");

                    b.Property<long>("LigtherTransformerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LigtherMetricId");

                    b.HasIndex("LigtherTransformerId");

                    b.ToTable("LigtherTransformerMetrics", "mup");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.LogbookDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("ElectricCompanyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LigtherMetricId")
                        .HasColumnType("bigint");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccuredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReportNumber")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<long?>("SystemLigtherId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ElectricCompanyId");

                    b.ToTable("LogbookDetails", "mup");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.MaintenanceFilesHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ElectricCompanyName")
                        .HasColumnType("longtext");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("longtext");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("PdfContent")
                        .HasColumnType("longblob");

                    b.Property<string>("ReportData")
                        .HasColumnType("json");

                    b.Property<string>("SystemLigtherName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("WorkOrderhNumber")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceFilesHistories", "mup");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.MeasurementSystemMaintenanceSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InstallationLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PeriodTo")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("Spreadsheet")
                        .HasColumnType("int");

                    b.Property<long>("SystemLigtherId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemLigtherId");

                    b.ToTable("MeasurementSystemMaintenanceSchedules", "mup");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.SystemLigther", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<long>("ElectricCompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlAuthorizationDocument")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ElectricCompanyId");

                    b.ToTable("SystemLigthers", "mup");
                });

            modelBuilder.Entity("MediUp.Infrastructure.Persistence.Entities.CustomAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AuditUser")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ModuleId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NewData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OldData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuditDate");

                    b.HasIndex("AuditUser");

                    b.HasIndex("EntityType");

                    b.HasIndex("Id");

                    b.HasIndex("IpAddress");

                    b.HasIndex("ModuleId");

                    b.HasIndex("EntityType", "EntityKey");

                    b.ToTable("AuditLog", "mup");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.Agent", b =>
                {
                    b.HasOne("MediUp.Domain.Entities.ElectriCompany", "ElectricCompany")
                        .WithMany("Agents")
                        .HasForeignKey("ElectricCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElectricCompany");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.CenaceMeasurementDetail", b =>
                {
                    b.HasOne("MediUp.Domain.Entities.CenaceMeasurement", "CenaceMeasurement")
                        .WithMany("CenaceMeasurementDetails")
                        .HasForeignKey("CenaceMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CenaceMeasurement");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.EnergyMeasurementData", b =>
                {
                    b.HasOne("MediUp.Domain.Entities.EnergyMeasurementDownload", "EnergyMeasurementDownload")
                        .WithMany("Data")
                        .HasForeignKey("EnergyMeasurementDownloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnergyMeasurementDownload");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.EnergyMeasurementEvent", b =>
                {
                    b.HasOne("MediUp.Domain.Entities.EnergyMeasurementDownload", "EnergyMeasurementDownload")
                        .WithMany("Events")
                        .HasForeignKey("EnergyMeasurementDownloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnergyMeasurementDownload");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.LigtherMetric", b =>
                {
                    b.HasOne("MediUp.Domain.Entities.SystemLigther", "SystemLigther")
                        .WithMany("LigtherMetrics")
                        .HasForeignKey("SystemLigtherId");

                    b.Navigation("SystemLigther");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.LigtherTransformer", b =>
                {
                    b.HasOne("MediUp.Domain.Entities.SystemLigther", "SystemLigther")
                        .WithMany("LigtherTransformers")
                        .HasForeignKey("SystemLigtherId");

                    b.Navigation("SystemLigther");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.LigtherTransformerMetric", b =>
                {
                    b.HasOne("MediUp.Domain.Entities.LigtherMetric", "LigtherMetric")
                        .WithMany("LigtherTransformerMetrics")
                        .HasForeignKey("LigtherMetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediUp.Domain.Entities.LigtherTransformer", "LigtherTransformer")
                        .WithMany("LigtherTransformerMetrics")
                        .HasForeignKey("LigtherTransformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LigtherMetric");

                    b.Navigation("LigtherTransformer");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.LogbookDetail", b =>
                {
                    b.HasOne("MediUp.Domain.Entities.ElectriCompany", "ElectricCompany")
                        .WithMany("LogbookDetails")
                        .HasForeignKey("ElectricCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElectricCompany");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.MeasurementSystemMaintenanceSchedule", b =>
                {
                    b.HasOne("MediUp.Domain.Entities.SystemLigther", "SystemLigther")
                        .WithMany("MeasurementSystemMaintenanceSchedules")
                        .HasForeignKey("SystemLigtherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemLigther");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.SystemLigther", b =>
                {
                    b.HasOne("MediUp.Domain.Entities.ElectriCompany", "ElectricCompany")
                        .WithMany("SystemLigthers")
                        .HasForeignKey("ElectricCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElectricCompany");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.CenaceMeasurement", b =>
                {
                    b.Navigation("CenaceMeasurementDetails");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.ElectriCompany", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("LogbookDetails");

                    b.Navigation("SystemLigthers");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.EnergyMeasurementDownload", b =>
                {
                    b.Navigation("Data");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.LigtherMetric", b =>
                {
                    b.Navigation("LigtherTransformerMetrics");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.LigtherTransformer", b =>
                {
                    b.Navigation("LigtherTransformerMetrics");
                });

            modelBuilder.Entity("MediUp.Domain.Entities.SystemLigther", b =>
                {
                    b.Navigation("LigtherMetrics");

                    b.Navigation("LigtherTransformers");

                    b.Navigation("MeasurementSystemMaintenanceSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
